$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root ".env"
$baseCompose = Join-Path $root "docker-compose.production.yml"
$prodOverride = Join-Path $root "docker-compose.prod.yml"
$ipOverride = Join-Path $root "docker-compose.ip.yml"

function Require-Command([string]$Name, [string]$Hint) {
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "[install] missing required command: $Name`n[install] hint: $Hint"
  }
}

function Normalize-ServerInput([string]$Value) {
  $normalized = $Value.Trim()
  $normalized = $normalized -replace '^https?://', ''
  $normalized = $normalized -replace '/.*$', ''
  $normalized = $normalized.Trim('/').Trim()
  return $normalized
}

function New-RandomHex([int]$BytesLength) {
  $bytes = New-Object byte[] $BytesLength
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $rng.GetBytes($bytes)
  $rng.Dispose()
  return -join ($bytes | ForEach-Object { $_.ToString("x2") })
}

function New-RandomBase64([int]$BytesLength) {
  $bytes = New-Object byte[] $BytesLength
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $rng.GetBytes($bytes)
  $rng.Dispose()
  return [Convert]::ToBase64String($bytes)
}

function Wait-HttpReady([string]$Url, [hashtable]$Headers = $null) {
  for ($i = 0; $i -lt 45; $i++) {
    try {
      if ($Headers) {
        Invoke-WebRequest -Uri $Url -Headers $Headers -UseBasicParsing -TimeoutSec 5 | Out-Null
      }
      else {
        Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 5 | Out-Null
      }
      return $true
    }
    catch {
      Start-Sleep -Seconds 2
    }
  }
  return $false
}

Require-Command "docker" "Install Docker Desktop or Docker Engine"
Require-Command "curl" "Install curl"
docker info | Out-Null

$composeMode = "docker-compose-plugin"
try {
  docker compose version | Out-Null
}
catch {
  if (Get-Command "docker-compose" -ErrorAction SilentlyContinue) {
    $composeMode = "docker-compose-legacy"
  }
  else {
    throw "[install] Docker Compose is missing (neither 'docker compose' nor 'docker-compose' found)."
  }
}

function Invoke-Compose {
  param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$Args
  )
  if ($composeMode -eq "docker-compose-legacy") {
    & docker-compose @Args
  }
  else {
    & docker compose @Args
  }
}

if (-not (Test-Path $baseCompose)) {
  throw "[install] missing compose file: $baseCompose"
}
if (-not (Test-Path $prodOverride)) {
  throw "[install] missing compose override file: $prodOverride"
}
if (-not (Test-Path $ipOverride)) {
  throw "[install] missing compose override file: $ipOverride"
}

$serverInput = Read-Host "Enter domain or IP"
$serverHost = Normalize-ServerInput $serverInput
if ([string]::IsNullOrWhiteSpace($serverHost)) {
  throw "[install] empty host value, aborting"
}

$parsedIp = $null
$isIp = [System.Net.IPAddress]::TryParse($serverHost, [ref]$parsedIp)
$mode = if ($isIp) { "ip" } else { "domain" }

if ($mode -eq "domain") {
  $defaultEmail = "admin@$serverHost"
  $emailInput = Read-Host "Email for TLS certificate [$defaultEmail]"
  $acmeEmail = if ([string]::IsNullOrWhiteSpace($emailInput)) { $defaultEmail } else { $emailInput.Trim() }
  $tlsEnabled = "true"
  $apiBase = "https://$serverHost"
  $wsUrl = "wss://$serverHost/ws"
  $relayPublishAddress = "127.0.0.1"
  $webPublishAddress = "127.0.0.1"
  $webPublishPort = "8081"
  $webAllowedOrigins = "https://$serverHost"
  $webTrustProxyHeaders = "true"
  $siteUrl = "https://$serverHost"
}
else {
  $acmeEmail = "install@localhost"
  $tlsEnabled = "false"
  $apiBase = "http://$serverHost:8080"
  $wsUrl = "ws://$serverHost:8080/ws"
  $relayPublishAddress = "0.0.0.0"
  $webPublishAddress = "0.0.0.0"
  $webPublishPort = "80"
  $webAllowedOrigins = "http://$serverHost"
  $webTrustProxyHeaders = "false"
  $siteUrl = "http://$serverHost"
}

$postgresDb = "secure_messenger"
$postgresUser = "secure_messenger"
$postgresPassword = New-RandomHex 16
$authTokenPepper = New-RandomHex 32
$securityEncryptionKey = New-RandomBase64 32
$databaseUrl = "postgres://{0}:{1}@postgres:5432/{2}?sslmode=disable" -f $postgresUser, $postgresPassword, $postgresDb
$transportAlternates = "$apiBase/api/v1/sync/poll"

if (Test-Path $envFile) {
  $backupPath = "$envFile.backup.$((Get-Date).ToString('yyyyMMddHHmmss'))"
  Copy-Item -Path $envFile -Destination $backupPath -Force
  Write-Host "[install] existing .env backed up to $backupPath"
}

$envContent = @"
# Auto-generated by scripts/install.ps1
PUBLIC_HOST=$serverHost
ACME_EMAIL=$acmeEmail
TLS_ENABLED=$tlsEnabled
API_BASE=$apiBase
WS_URL=$wsUrl

APP_ENV=production
LOG_LEVEL=info
HTTP_HOST=0.0.0.0
HTTP_PORT=8080
HEALTH_PATH=/health
READY_PATH=/ready
WS_PATH=/ws
API_PREFIX=/api/v1
RUN_MIGRATIONS_ON_START=true

POSTGRES_DB=$postgresDb
POSTGRES_USER=$postgresUser
POSTGRES_PASSWORD=$postgresPassword
DATABASE_URL=$databaseUrl

AUTH_TOKEN_PEPPER=$authTokenPepper
SECURITY_ENCRYPTION_KEY=$securityEncryptionKey

AUTH_ACCESS_TOKEN_TTL_MIN=15
AUTH_REFRESH_TOKEN_TTL_HOURS=720
AUTH_2FA_CHALLENGE_TTL_MIN=5
AUTH_2FA_ISSUER=SecureMessenger

MESSAGING_ATTACHMENTS_DIR=/app/data/attachments
MESSAGING_ATTACHMENT_MAX_BYTES=20971520
MESSAGING_UNATTACHED_TTL_HOURS=24

TRANSPORT_PRIMARY_WS_ENDPOINT=$wsUrl
TRANSPORT_ALTERNATE_ENDPOINTS=$transportAlternates
TRANSPORT_WS_QUERY_TOKEN_FALLBACK=false
TRANSPORT_LONG_POLL_ENABLED=true
TRANSPORT_LONG_POLL_TIMEOUT_SEC=25
TRANSPORT_RECONNECT_BACKOFF_MIN_MS=500
TRANSPORT_RECONNECT_BACKOFF_MAX_MS=10000

HTTP_READ_TIMEOUT_SEC=10
HTTP_WRITE_TIMEOUT_SEC=10
HTTP_IDLE_TIMEOUT_SEC=60
HTTP_SHUTDOWN_TIMEOUT_SEC=10

RELAY_PUBLISH_ADDRESS=$relayPublishAddress
RELAY_PUBLISH_PORT=8080
WEB_PUBLISH_ADDRESS=$webPublishAddress
WEB_PUBLISH_PORT=$webPublishPort

WEB_ALLOWED_ORIGINS=$webAllowedOrigins
WEB_ALLOW_TAURI_ORIGIN=true
WEB_ALLOW_NULL_ORIGIN=false
WEB_ALLOW_LOCALHOST_ORIGIN=false
WEB_ALLOW_LOCALHOST_SUBDOMAINS=false
WEB_TRUST_PROXY_HEADERS=$webTrustProxyHeaders
WEB_SESSION_DEFAULT_PERSISTENCE=ephemeral
WEB_SESSION_ALLOW_REMEMBERED=true
"@

[System.IO.File]::WriteAllText($envFile, $envContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "[install] .env generated: $envFile"

if ($mode -eq "domain") {
  $composeOverride = $prodOverride
}
else {
  $composeOverride = $ipOverride
}

$composeArgs = @("-f", $baseCompose, "-f", $composeOverride, "--env-file", $envFile)

Write-Host "[install] removing old orphan containers (if any)"
try {
  Invoke-Compose @composeArgs down --remove-orphans | Out-Null
}
catch {
  # Best effort cleanup.
}

if ($mode -eq "domain") {
  Write-Host "[install] starting stack in DOMAIN mode (TLS via Caddy)"
  Invoke-Compose @composeArgs up -d --build --remove-orphans
  $healthUrl = "https://$serverHost/health"
  $readyUrl = "https://$serverHost/ready"
  $configUrl = "https://$serverHost/api/v1/config"
  $siteHealthUrl = "https://$serverHost/"
  $fallbackHealthUrl = "http://127.0.0.1/health"
}
else {
  Write-Host "[install] starting stack in IP mode (HTTP + Web UI + API)"
  Invoke-Compose @composeArgs up -d --build --remove-orphans
  $healthUrl = "http://$serverHost:8080/health"
  $readyUrl = "http://$serverHost:8080/ready"
  $configUrl = "http://$serverHost:8080/api/v1/config"
  $siteHealthUrl = "http://$serverHost/healthz"
  $fallbackHealthUrl = $null
}

Write-Host "[install] waiting for health: $healthUrl"
$healthOk = Wait-HttpReady -Url $healthUrl
if (-not $healthOk -and $mode -eq "domain") {
  $healthOk = Wait-HttpReady -Url $fallbackHealthUrl -Headers @{ Host = $serverHost }
  if ($healthOk) {
    Write-Host "[install] public health check is not reachable yet, but local edge check passed."
  }
}

if (-not $healthOk) {
  Invoke-Compose @composeArgs ps
  Invoke-Compose @composeArgs logs --tail=150
  throw "[install] health check failed"
}

if (-not (Wait-HttpReady -Url $readyUrl)) {
  Write-Warning "[install] warning: readiness endpoint is not reachable yet at $readyUrl"
}
if (-not (Wait-HttpReady -Url $configUrl)) {
  Write-Warning "[install] warning: /api/v1/config is not reachable yet at $configUrl"
}
if (-not (Wait-HttpReady -Url $siteHealthUrl)) {
  Write-Warning "[install] warning: web UI endpoint is not reachable yet at $siteHealthUrl"
}

Invoke-Compose @composeArgs ps

Write-Host ""
Write-Host "=============================="
Write-Host "SERVER READY"
Write-Host ""
Write-Host "Site:"
Write-Host $siteUrl
Write-Host ""
Write-Host "API:"
Write-Host $apiBase
Write-Host ""
Write-Host "Web client connects to server automatically"
Write-Host "=============================="
