#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
BASE_COMPOSE_FILE="$ROOT_DIR/docker-compose.production.yml"
PROD_OVERRIDE_FILE="$ROOT_DIR/docker-compose.prod.yml"

require_command() {
  local command_name="$1"
  local install_hint="$2"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "[install] missing required command: $command_name" >&2
    echo "[install] hint: $install_hint" >&2
    exit 1
  fi
}

trim() {
  echo "$1" | tr -d '\r' | xargs
}

normalize_server_input() {
  local raw
  raw="$(trim "$1")"
  raw="${raw#http://}"
  raw="${raw#https://}"
  raw="${raw%%/*}"
  raw="${raw%/}"
  echo "$raw"
}

is_ipv4() {
  local value="$1"
  if [[ ! "$value" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    return 1
  fi

  local part
  IFS='.' read -r -a parts <<<"$value"
  for part in "${parts[@]}"; do
    if (( part < 0 || part > 255 )); then
      return 1
    fi
  done
  return 0
}

generate_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi
  if [[ -r /dev/urandom ]]; then
    od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
    return
  fi
  echo "[install] cannot generate random hex (openssl or /dev/urandom required)" >&2
  exit 1
}

generate_base64() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$bytes" | tr -d '\n'
    return
  fi
  if [[ -r /dev/urandom ]]; then
    head -c "$bytes" /dev/urandom | base64 | tr -d '\n'
    return
  fi
  echo "[install] cannot generate random base64 (openssl or /dev/urandom required)" >&2
  exit 1
}

wait_for_http() {
  local url="$1"
  local host_header="${2:-}"

  local attempts=45
  local attempt=1
  while (( attempt <= attempts )); do
    if [[ -n "$host_header" ]]; then
      if curl -fsS --max-time 5 -H "Host: $host_header" "$url" >/dev/null 2>&1; then
        return 0
      fi
    else
      if curl -fsS --max-time 5 "$url" >/dev/null 2>&1; then
        return 0
      fi
    fi
    sleep 2
    (( attempt += 1 ))
  done
  return 1
}

require_command docker "install Docker Engine"
require_command curl "install curl"

if ! docker info >/dev/null 2>&1; then
  echo "[install] Docker daemon is not running or not accessible." >&2
  exit 1
fi

if docker compose version >/dev/null 2>&1; then
  COMPOSE_BIN=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE_BIN=(docker-compose)
else
  echo "[install] Docker Compose is missing (neither 'docker compose' nor 'docker-compose' found)." >&2
  exit 1
fi

if [[ ! -f "$BASE_COMPOSE_FILE" ]]; then
  echo "[install] missing compose file: $BASE_COMPOSE_FILE" >&2
  exit 1
fi

if [[ ! -f "$PROD_OVERRIDE_FILE" ]]; then
  echo "[install] missing compose override file: $PROD_OVERRIDE_FILE" >&2
  exit 1
fi

read -rp "Введите домен или IP: " server_input
server_host="$(normalize_server_input "$server_input")"

if [[ -z "$server_host" ]]; then
  echo "[install] empty host value, aborting." >&2
  exit 1
fi

mode="domain"
if is_ipv4 "$server_host"; then
  mode="ip"
fi

if [[ "$mode" == "domain" ]]; then
  default_email="admin@$server_host"
  read -rp "Email для TLS сертификата [${default_email}]: " acme_email
  acme_email="$(trim "${acme_email:-$default_email}")"
  if [[ -z "$acme_email" ]]; then
    acme_email="$default_email"
  fi
  tls_enabled="true"
  api_base="https://${server_host}"
  ws_url="wss://${server_host}/ws"
  relay_publish_address="127.0.0.1"
else
  acme_email="install@localhost"
  tls_enabled="false"
  api_base="http://${server_host}:8080"
  ws_url="ws://${server_host}:8080/ws"
  relay_publish_address="0.0.0.0"
fi

postgres_db="secure_messenger"
postgres_user="secure_messenger"
postgres_password="$(generate_hex 16)"
auth_token_pepper="$(generate_hex 32)"
security_encryption_key="$(generate_base64 32)"
database_url="postgres://${postgres_user}:${postgres_password}@postgres:5432/${postgres_db}?sslmode=disable"
transport_alternates="${api_base}/api/v1/sync/poll"

if [[ -f "$ENV_FILE" ]]; then
  backup_path="${ENV_FILE}.backup.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$backup_path"
  echo "[install] existing .env backed up to $backup_path"
fi

cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/install.sh
PUBLIC_HOST=${server_host}
ACME_EMAIL=${acme_email}
TLS_ENABLED=${tls_enabled}
API_BASE=${api_base}
WS_URL=${ws_url}

APP_ENV=production
LOG_LEVEL=info
HTTP_HOST=0.0.0.0
HTTP_PORT=8080
HEALTH_PATH=/health
READY_PATH=/ready
WS_PATH=/ws
API_PREFIX=/api/v1
RUN_MIGRATIONS_ON_START=true

POSTGRES_DB=${postgres_db}
POSTGRES_USER=${postgres_user}
POSTGRES_PASSWORD=${postgres_password}
DATABASE_URL=${database_url}

AUTH_TOKEN_PEPPER=${auth_token_pepper}
SECURITY_ENCRYPTION_KEY=${security_encryption_key}

AUTH_ACCESS_TOKEN_TTL_MIN=15
AUTH_REFRESH_TOKEN_TTL_HOURS=720
AUTH_2FA_CHALLENGE_TTL_MIN=5
AUTH_2FA_ISSUER=SecureMessenger

MESSAGING_ATTACHMENTS_DIR=/app/data/attachments
MESSAGING_ATTACHMENT_MAX_BYTES=20971520
MESSAGING_UNATTACHED_TTL_HOURS=24

TRANSPORT_PRIMARY_WS_ENDPOINT=${ws_url}
TRANSPORT_ALTERNATE_ENDPOINTS=${transport_alternates}
TRANSPORT_WS_QUERY_TOKEN_FALLBACK=false
TRANSPORT_LONG_POLL_ENABLED=true
TRANSPORT_LONG_POLL_TIMEOUT_SEC=25
TRANSPORT_RECONNECT_BACKOFF_MIN_MS=500
TRANSPORT_RECONNECT_BACKOFF_MAX_MS=10000

HTTP_READ_TIMEOUT_SEC=10
HTTP_WRITE_TIMEOUT_SEC=10
HTTP_IDLE_TIMEOUT_SEC=60
HTTP_SHUTDOWN_TIMEOUT_SEC=10

RELAY_PUBLISH_ADDRESS=${relay_publish_address}
RELAY_PUBLISH_PORT=8080
EOF

echo "[install] .env generated: $ENV_FILE"

compose_cmd=("${COMPOSE_BIN[@]}" -f "$BASE_COMPOSE_FILE" -f "$PROD_OVERRIDE_FILE" --env-file "$ENV_FILE")

echo "[install] removing old orphan containers (if any)"
"${compose_cmd[@]}" down --remove-orphans >/dev/null 2>&1 || true

if [[ "$mode" == "domain" ]]; then
  echo "[install] starting stack in DOMAIN mode (TLS via Caddy)"
  "${compose_cmd[@]}" up -d --build --remove-orphans
  health_url="https://${server_host}/health"
  ready_url="https://${server_host}/ready"
  config_url="https://${server_host}/api/v1/config"
  fallback_health_url="http://127.0.0.1/health"
else
  echo "[install] starting stack in IP mode (direct HTTP on :8080, no Caddy)"
  "${compose_cmd[@]}" up -d --build --remove-orphans postgres relay-server
  health_url="http://${server_host}:8080/health"
  ready_url="http://${server_host}:8080/ready"
  config_url="http://${server_host}:8080/api/v1/config"
  fallback_health_url=""
fi

echo "[install] waiting for health: $health_url"
if ! wait_for_http "$health_url"; then
  if [[ -n "$fallback_health_url" ]] && wait_for_http "$fallback_health_url" "$server_host"; then
    echo "[install] public health check is not reachable yet, but local edge check passed."
  else
    echo "[install] health check failed." >&2
    "${compose_cmd[@]}" ps || true
    "${compose_cmd[@]}" logs --tail=150 || true
    exit 1
  fi
fi

if ! wait_for_http "$ready_url"; then
  echo "[install] warning: readiness endpoint is not reachable yet at $ready_url" >&2
fi

if ! wait_for_http "$config_url"; then
  echo "[install] warning: /api/v1/config is not reachable yet at $config_url" >&2
fi

"${compose_cmd[@]}" ps

printf '\n==============================\n'
printf 'СЕРВЕР ГОТОВ\n\n'
printf 'Адрес:\n%s\n\n' "$api_base"
printf 'Введите этот адрес в клиенте\n'
printf '==============================\n'
