$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root ".env"
$baseCompose = Join-Path $root "docker-compose.production.yml"
$prodOverride = Join-Path $root "docker-compose.prod.yml"

function Require-Command([string]$Name, [string]$Hint) {
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "[install] missing required command: $Name`n[install] hint: $Hint"
  }
}

function Normalize-ServerInput([string]$Value) {
  $normalized = $Value.Trim()
  $normalized = $normalized -replace '^https?://', ''
  $normalized = $normalized -replace '/.*$', ''
  $normalized = $normalized.Trim('/').Trim()
  return $normalized
}

function New-RandomHex([int]$BytesLength) {
  $bytes = New-Object byte[] $BytesLength
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $rng.GetBytes($bytes)
  $rng.Dispose()
  return -join ($bytes | ForEach-Object { $_.ToString("x2") })
}

function New-RandomBase64([int]$BytesLength) {
  $bytes = New-Object byte[] $BytesLength
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $rng.GetBytes($bytes)
  $rng.Dispose()
  return [Convert]::ToBase64String($bytes)
}

function Wait-HttpReady([string]$Url, [hashtable]$Headers = $null) {
  for ($i = 0; $i -lt 45; $i++) {
    try {
      if ($Headers) {
        Invoke-WebRequest -Uri $Url -Headers $Headers -UseBasicParsing -TimeoutSec 5 | Out-Null
      }
      else {
        Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 5 | Out-Null
      }
      return $true
    }
    catch {
      Start-Sleep -Seconds 2
    }
  }
  return $false
}

Require-Command "docker" "Install Docker Desktop or Docker Engine"
Require-Command "curl" "Install curl"

docker info | Out-Null
docker compose version | Out-Null

if (-not (Test-Path $baseCompose)) {
  throw "[install] missing compose file: $baseCompose"
}
if (-not (Test-Path $prodOverride)) {
  throw "[install] missing compose override file: $prodOverride"
}

$serverInput = Read-Host "Введите домен или IP"
$serverHost = Normalize-ServerInput $serverInput
if ([string]::IsNullOrWhiteSpace($serverHost)) {
  throw "[install] empty host value, aborting"
}

$parsedIp = $null
$isIp = [System.Net.IPAddress]::TryParse($serverHost, [ref]$parsedIp)
$mode = if ($isIp) { "ip" } else { "domain" }

if ($mode -eq "domain") {
  $defaultEmail = "admin@$serverHost"
  $emailInput = Read-Host "Email для TLS сертификата [$defaultEmail]"
  $acmeEmail = if ([string]::IsNullOrWhiteSpace($emailInput)) { $defaultEmail } else { $emailInput.Trim() }
  $tlsEnabled = "true"
  $apiBase = "https://$serverHost"
  $wsUrl = "wss://$serverHost/ws"
  $relayPublishAddress = "127.0.0.1"
}
else {
  $acmeEmail = "install@localhost"
  $tlsEnabled = "false"
  $apiBase = "http://$serverHost:8080"
  $wsUrl = "ws://$serverHost:8080/ws"
  $relayPublishAddress = "0.0.0.0"
}

$postgresDb = "secure_messenger"
$postgresUser = "secure_messenger"
$postgresPassword = New-RandomHex 16
$authTokenPepper = New-RandomHex 32
$securityEncryptionKey = New-RandomBase64 32
$databaseUrl = "postgres://${postgresUser}:${postgresPassword}@postgres:5432/${postgresDb}?sslmode=disable"
$transportAlternates = "$apiBase/api/v1/sync/poll"

if (Test-Path $envFile) {
  $backupPath = "$envFile.backup.$((Get-Date).ToString('yyyyMMddHHmmss'))"
  Copy-Item -Path $envFile -Destination $backupPath -Force
  Write-Host "[install] existing .env backed up to $backupPath"
}

$envContent = @"
# Auto-generated by scripts/install.ps1
PUBLIC_HOST=$serverHost
ACME_EMAIL=$acmeEmail
TLS_ENABLED=$tlsEnabled
API_BASE=$apiBase
WS_URL=$wsUrl

APP_ENV=production
LOG_LEVEL=info
HTTP_HOST=0.0.0.0
HTTP_PORT=8080
HEALTH_PATH=/health
READY_PATH=/ready
WS_PATH=/ws
API_PREFIX=/api/v1
RUN_MIGRATIONS_ON_START=false

POSTGRES_DB=$postgresDb
POSTGRES_USER=$postgresUser
POSTGRES_PASSWORD=$postgresPassword
DATABASE_URL=$databaseUrl

AUTH_TOKEN_PEPPER=$authTokenPepper
SECURITY_ENCRYPTION_KEY=$securityEncryptionKey

AUTH_ACCESS_TOKEN_TTL_MIN=15
AUTH_REFRESH_TOKEN_TTL_HOURS=720
AUTH_2FA_CHALLENGE_TTL_MIN=5
AUTH_2FA_ISSUER=SecureMessenger

MESSAGING_ATTACHMENTS_DIR=/app/data/attachments
MESSAGING_ATTACHMENT_MAX_BYTES=20971520
MESSAGING_UNATTACHED_TTL_HOURS=24

TRANSPORT_PRIMARY_WS_ENDPOINT=$wsUrl
TRANSPORT_ALTERNATE_ENDPOINTS=$transportAlternates
TRANSPORT_WS_QUERY_TOKEN_FALLBACK=false
TRANSPORT_LONG_POLL_ENABLED=true
TRANSPORT_LONG_POLL_TIMEOUT_SEC=25
TRANSPORT_RECONNECT_BACKOFF_MIN_MS=500
TRANSPORT_RECONNECT_BACKOFF_MAX_MS=10000

HTTP_READ_TIMEOUT_SEC=10
HTTP_WRITE_TIMEOUT_SEC=10
HTTP_IDLE_TIMEOUT_SEC=60
HTTP_SHUTDOWN_TIMEOUT_SEC=10

RELAY_PUBLISH_ADDRESS=$relayPublishAddress
RELAY_PUBLISH_PORT=8080
"@

[System.IO.File]::WriteAllText($envFile, $envContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "[install] .env generated: $envFile"

$composeArgs = @("compose", "-f", $baseCompose, "-f", $prodOverride, "--env-file", $envFile)

if ($mode -eq "domain") {
  Write-Host "[install] starting stack in DOMAIN mode (TLS via Caddy)"
  docker @composeArgs up -d --build
  $healthUrl = "https://$serverHost/health"
  $configUrl = "https://$serverHost/api/v1/config"
  $fallbackHealthUrl = "http://127.0.0.1/health"
}
else {
  Write-Host "[install] starting stack in IP mode (direct HTTP on :8080, no Caddy)"
  docker @composeArgs up -d --build postgres relay-migrate relay-server
  $healthUrl = "http://$serverHost:8080/health"
  $configUrl = "http://$serverHost:8080/api/v1/config"
  $fallbackHealthUrl = $null
}

Write-Host "[install] waiting for health: $healthUrl"
$healthOk = Wait-HttpReady -Url $healthUrl
if (-not $healthOk -and $mode -eq "domain") {
  $healthOk = Wait-HttpReady -Url $fallbackHealthUrl -Headers @{ Host = $serverHost }
  if ($healthOk) {
    Write-Host "[install] public health check is not reachable yet, but local edge check passed."
  }
}

if (-not $healthOk) {
  docker @composeArgs ps
  docker @composeArgs logs --tail=120
  throw "[install] health check failed"
}

if (-not (Wait-HttpReady -Url $configUrl)) {
  Write-Warning "[install] warning: /api/v1/config is not reachable yet at $configUrl"
}

docker @composeArgs ps

Write-Host ""
Write-Host "=============================="
Write-Host "СЕРВЕР ГОТОВ"
Write-Host ""
Write-Host "Адрес:"
Write-Host $apiBase
Write-Host ""
Write-Host "Введите этот адрес в клиенте"
Write-Host "=============================="
